// Build-time generator replacing three Pangolin CMake code-generation steps
// so the upstream sources can compile under Bazel without CMake:
//
//   --mode=binary  - cmake/EmbedBinaryFiles.cmake
//                    (fonts.cpp: byte arrays from *.ttf)
//   --mode=shader  - cmake/EmbedShaderFiles.cmake
//                    (shaders.cpp: builtin GLSL source map)
//   --mode=factory - cmake/PangolinFactory.cmake
//                    (RegisterFactories<Interface>.h headers)
//
// The output formats match the CMake versions semantically; it is compiled
// for the exec configuration by tools/embed.bzl via ctx.actions.run.

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

std::string BaseName(const std::string& path) {
  size_t pos = path.find_last_of("/\\");
  return pos == std::string::npos ? path : path.substr(pos + 1);
}

// Mirrors the CMake regex: replace filename spaces and extension separators
// for C compatibility ("AnonymousPro.ttf" -> "AnonymousPro_ttf").
std::string SymbolName(const std::string& path) {
  std::string name = BaseName(path);
  for (char& c : name) {
    if (c == '.' || c == ' ') c = '_';
  }
  return name;
}

bool ReadFile(const std::string& path, std::string* out, bool binary) {
  std::ifstream f(path, binary ? (std::ios::in | std::ios::binary) : std::ios::in);
  if (!f) {
    std::cerr << "gen_embed: cannot open " << path << std::endl;
    return false;
  }
  std::ostringstream ss;
  ss << f.rdbuf();
  *out = ss.str();
  return true;
}

bool WriteFile(const std::string& path, const std::string& content) {
  std::ofstream f(path, std::ios::out | std::ios::binary);
  if (!f) {
    std::cerr << "gen_embed: cannot write " << path << std::endl;
    return false;
  }
  f << content;
  return f.good();
}

// cmake/EmbedBinaryFiles.cmake equivalent.
std::string EmitBinary(const std::vector<std::string>& inputs) {
  std::string out;
  for (const std::string& input : inputs) {
    std::string data;
    if (!ReadFile(input, &data, /*binary=*/true)) std::exit(1);
    out += "extern const unsigned char " + SymbolName(input) + "[] = {";
    static const char* kHex = "0123456789abcdef";
    for (size_t i = 0; i < data.size(); ++i) {
      unsigned char byte = static_cast<unsigned char>(data[i]);
      out += std::string("0x") + kHex[byte >> 4] + kHex[byte & 0xf] + ",";
    }
    out += "};\n";
    out += "extern const unsigned " + SymbolName(input) +
           "_size = sizeof(" + SymbolName(input) + ");\n";
  }
  return out;
}

// cmake/EmbedShaderFiles.cmake equivalent. Map keys are the shader paths
// relative to the Pangolin project root, matching upstream.
std::string EmitShaders(const std::string& prefix,
                        const std::vector<std::string>& inputs) {
  std::string out;
  out += "#include <unordered_map>\n";
  out += "#include <string>\n\n";
  out += "namespace pangolin {\n";
  out += "const std::unordered_map<std::string,const char*>& GetBuiltinShaders() {\n";
  out += "\tstatic const std::unordered_map<std::string,const char*> builtin_shaders = {\n";
  for (const std::string& input : inputs) {
    std::string data;
    if (!ReadFile(input, &data, /*binary=*/false)) std::exit(1);
    out += "{ \"" + prefix + "/" + BaseName(input) + "\",\n R\"SHADER_SOURCE(\n";
    out += data;
    out += ")SHADER_SOURCE\" },\n";
  }
  out += "\t};\n";
  out += "\treturn builtin_shaders;\n";
  out += "}\n";
  out += "}\n";
  return out;
}

// cmake/PangolinFactory.cmake create_factory_registry_file_now() equivalent.
std::string EmitFactory(const std::string& interface,
                        const std::vector<std::string>& factories) {
  std::string out;
  out += "// Generated by rules_pangolin (gen_embed). Do Not Edit.\n\n";
  out += "#pragma once\n\n";
  out += "namespace pangolin {\n\n";
  out += "  // Forward declarations\n";
  for (const std::string& factory : factories) {
    out += "  bool Register" + factory + "Factory();\n";
  }
  out += "\n\n";
  out += "  inline bool RegisterFactories" + interface + "() {\n";
  out += "    bool success = true;\n";
  for (const std::string& factory : factories) {
    out += "    success &= Register" + factory + "Factory();\n";
  }
  out += "    return success;\n";
  out += "  }\n";
  out += "\n\n} // pangolin\n";
  return out;
}

void Usage() {
  std::cerr << "usage: gen_embed --mode=binary|shader|factory -o OUT"
            << " [--prefix=P] [--interface=I] [--factory=F ...] INPUT..."
            << std::endl;
}

}  // namespace

int main(int argc, char** argv) {
  std::string mode;
  std::string output;
  std::string prefix;
  std::string interface;
  std::vector<std::string> factories;
  std::vector<std::string> inputs;

  for (int i = 1; i < argc; ++i) {
    std::string arg = argv[i];
    if (arg == "--mode=binary" || arg == "--mode=shader" || arg == "--mode=factory") {
      mode = arg.substr(7);
    } else if (arg == "-o" && i + 1 < argc) {
      output = argv[++i];
    } else if (arg.rfind("--prefix=", 0) == 0) {
      prefix = arg.substr(9);
    } else if (arg.rfind("--interface=", 0) == 0) {
      interface = arg.substr(12);
    } else if (arg.rfind("--factory=", 0) == 0) {
      factories.push_back(arg.substr(10));
    } else if (arg == "--help" || arg == "-h") {
      Usage();
      return 0;
    } else {
      inputs.push_back(arg);
    }
  }

  if (mode.empty() || output.empty()) {
    Usage();
    return 1;
  }
  if ((mode == "shader" || mode == "binary") && inputs.empty()) {
    Usage();
    return 1;
  }
  if (mode == "factory" && (interface.empty() || factories.empty())) {
    Usage();
    return 1;
  }

  std::string content;
  if (mode == "binary") {
    content = EmitBinary(inputs);
  } else if (mode == "shader") {
    content = EmitShaders(prefix, inputs);
  } else {
    content = EmitFactory(interface, factories);
  }

  return WriteFile(output, content) ? 0 : 1;
}
