"""Repository rule that exposes this module's tools/ directory as a
generated repository.

The @pangolin overlay BUILD file loads its Starlark codegen rules and its
code generator from the sibling repository created here; repositories
generated by the same module extension can reference each other by their
plain names, which keeps the overlay free of any rules_pangolin-specific
canonical repo names.
"""

_TOOLS_FILES = [
    "//tools:BUILD.bazel",
    "//tools:gen_embed.cc",
    "//tools:embed.bzl",
]

def _impl(ctx):
    # The repository root must be a real directory, so the tools/ files are
    # symlinked individually; the symlinked BUILD.bazel defines the
    # `gen_embed` cc_binary used as the exec tool.
    for src in ctx.attr.srcs:
        ctx.symlink(ctx.path(src), src.name)

pangolin_tools_repository = repository_rule(
    implementation = _impl,
    attrs = {
        "srcs": attr.label_list(default = _TOOLS_FILES),
    },
)
